#pragma config(Motor,  port2,           FrontLaunch,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           BackLaunch,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		if (vexRT(Btn8D) == 1)
		{
			motor[FrontLaunch] = 127;
			motor[BackLaunch] = 127;
			wait1Msec(5000);
			motor[FrontLaunch] = 0;
			motor[BackLaunch] = 0;
		}
		//else if (vexRT(Btn8D) != 1)
		//{
		//motor[FrontLaunch] = 0;
		//motor[BackLaunch] = 0;
		//}
	}
}
