#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    bat,            sensorNone)
#pragma config(Sensor, in8,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  RedOrBlue,      sensorDigitalIn)
#pragma config(Sensor, dgtl2,  SkyOrNot,       sensorDigitalIn)
#pragma config(Sensor, dgtl3,  graypost,       sensorTouch)
#pragma config(Sensor, I2C_1,  LeftShootE,     sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  RightShootE,    sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           intakeMot,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port3,           backRight,     tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           LeftShoot,     tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port6,           RightShoot,    tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port8,           frontLeft,     tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port9,           backLeft,      tmotorVex393_MC29, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"


/////////////////////////////////
void pre_auton()
{
}

//********************************************************************************************************************************************************
task autonomous()
{
task usercontrol()
{
	startTask(lcd);
	,  Wrist1=0, Arm1=0, wtime = 0, desiredangle = 0;
	int gyropos = 0, angle = 0, direction = 0, holdthearm = 0, holdthewrist = 0;
	, JVI = 1, slowdown = 0, armholdpos = 0, wristholdangle = 0;
	int spinfast=50, spinslow=30;

	//Create "deadzone" variables. Adjust threshold value to increase/decrease deadzone
	//enter user hcontrol segment
	//Loop Forever
	//clearDebugStream();
	while(1)
	{
		//%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
		//create deadzones ALSO SLOWS DOWN THE ROBOT BY "SLOWDOWN" IF SELECTED
	}
}
