#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    bat,            sensorAnalog)
#pragma config(Sensor, in8,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  RedOrBlue,      sensorDigitalIn)
#pragma config(Sensor, dgtl2,  LeftOrNot,      sensorDigitalIn)
#pragma config(Sensor, dgtl3,  Skils,          sensorDigitalIn)
#pragma config(Sensor, I2C_1,  intmotencFL,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  intmotencBL,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  intmotencBR,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  intmotencARM,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  intmotencW,     sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_6,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           pincer,        tmotorVex393_HBridge, openLoop, encoderPort, I2C_6)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop, reversed, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port3,           backRight,     tmotorVex393_MC29, openLoop, reversed, driveRight, encoderPort, I2C_1)
#pragma config(Motor,  port4,           topRight,      tmotorVex393_MC29, openLoop, driveRight, encoderPort, I2C_5)
#pragma config(Motor,  port5,           bottomRight,   tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,           topLeft,       tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port7,           bottomLeft,    tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port8,           frontLeft,     tmotorVex393_MC29, openLoop, driveLeft, encoderPort, I2C_3)
#pragma config(Motor,  port9,           backLeft,      tmotorVex393_MC29, openLoop, driveLeft, encoderPort, I2C_4)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

//varables
int up = 900;
int throw = 1100;
int Pickup = 125;
int down = 0;
int drive = 500;
int armHol = 0;
int nockStar = 900;
int pos = 125;
//speeds
const int highspd = 127;
const int medspd = 95;
const int lowspd = 40;

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "11-15-16 includes.c"				 //main user code has all the voids...no need to modify.

void pre_auton()
{
	bStopTasksBetweenModes = true;
	//reset incoders
	nMotorEncoder[frontLeft]=0;
	nMotorEncoder[frontRight]=0;
	nMotorEncoder[backLeft]=0;
	nMotorEncoder[backRight]=0;
	nMotorEncoder[topRight]=0;
	//reset gyro
	SensorType[gyro] = 0;
	wait1Msec(50);
	SensorType[gyro] = sensorGyro;
	wait1Msec(1300);
	//angle is in degrees - multiplying by 10 done in the turn function
	//Adjust SensorFullCount to set the "rollover" point. A value of 3600 sets the rollover point to +/-3600
	SensorFullCount[gyro] = 7200;
}

task autonomous()
{
	startTask(lcdAndArm);
	//turnrobot(angle,direction,speed);
	//moverobot(xx1,xx2,yy1,duration,automode,speed)
	//movearm (speed,duration,holdarm,holdarmpos)
	/*
	if (SensorValue[RedOrBlue] == 0) //blue
	{
	if (SensorValue[SkyOrNot] == 0)//blue left
	{

	}
	if (SensorValue[SkyOrNot] == 1)//blue Right
	{

	}
	}
	if (SensorValue[RedOrBlue] == 1)//red
	{
	if (SensorValue[SkyOrNot] == 0) //red right
	{

	}
	if (SensorValue[SkyOrNot] == 1)//red left
	{
	}
	}
	*/
	if(SensorValue[Skils] == 1)//skills feald
	{
		win();
	}
}

task usercontrol()
{
	//turnrobot(angle,direction,speed);
	//moverobot(xx1,xx2,yy1,duration,automode,speed)
	//void movearm(speed,duration,holdarm,holdarmpos)
	startTask(lcdAndArm);
	int X1 = 0, Y1 = 0, X2 = 0,Y2 = 0;
	int threshold = 20;
	while (true)
	{
		//Create "deadzone" for Y1/Ch3 (FORWARD/BACK)
		Y1 = (abs(vexRT[Ch3]) > threshold) ? (vexRT[Ch3]) : (0);
		//Create "deadzone" for X1/Ch4 (RIGHT/LEFT)
		X1 = (abs(vexRT[Ch4]) > threshold) ? (vexRT[Ch4]) : (0);
		//Create "deadzone" for X2/Ch1(Rotation of robot about z axis)
		X2 = (abs(vexRT[Ch1]) > threshold+10) ? (vexRT[Ch1]*2/3) : (0);
		//Create "deadzone" for X2/Ch1(Rotation of robot about z axis)
		Y2 = (abs(vexRT[Ch3Xmtr2]) > threshold+10) ? (vexRT[Ch3Xmtr2]*2/3) : (0);
		//call robot movement function
		moverobot(X1,X2,Y1*0.8,0,0,0);
		//put arm in throw position
		if(vexRT[Btn8UXmtr2] == 1)
		{
			armHol = 1;
			movearm(highspd,0,1,throw);
		}
		//put arm in picup position
		if(vexRT[Btn8DXmtr2] == 1)
		{
			armHol = 1;
			movearm(lowspd+10,0,1,Pickup);
		}
		//put arm in drive
		if(vexRT[Btn8RXmtr2] == 1)
		{
			armHol = 1;
			movearm(lowspd+15,0,1,drive);
		}
		//put arm in knock off
		if(vexRT[Btn8LXmtr2] == 1)
		{
			armHol = 1;
			movearm(lowspd+15,0,1,nockStar);
		}
		//set pos
		if(vexRT[Btn6UXmtr2] == 1)
		{
			pos = nMotorEncoder[topRight];
		}
		//hold pos
		if(vexRT[Btn6DXmtr2] == 1)
		{
			armHol = 1;
			movearm(lowspd+15,0,1,pos);
		}

		//joy controel
		if(armHol == 0)
		{
			movearm(Y2,0,0,0);
		}
		//lock and unlock arm controel
		if(vexRT[Btn5UXmtr2] == 1)
		{
			armHol = 1;
		}
		if(vexRT[Btn5DXmtr2] == 1)
		{
			armHol = 0;
		}
	}
}
