#pragma config(Motor,  port2,           motor1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           motor2,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task run_motor2()
{
	motor[motor2] = 127;
	motor[motor1] = 0;
}

task main()
{
	motor[motor1] = 127;
	while(1)
	{
		if(vexRT[btn8D] == 1)
		{
			startTask(run_motor2);
		}
	}
}
