//add to main
//#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
//#pragma config(I2C_Usage, I2C1, i2cSensors)
//#pragma config(Sensor, in1,    bat,            sensorNone)
//#pragma config(Sensor, I2C_1,  intmotencFL,    sensorQuadEncoderOnI2CPort,    , AutoAssign)
//#pragma config(Sensor, I2C_2,  intmotencBL,    sensorQuadEncoderOnI2CPort,    , AutoAssign)
//#pragma config(Sensor, I2C_3,  intmotencBR,    sensorQuadEncoderOnI2CPort,    , AutoAssign)
//#pragma config(Sensor, I2C_4,  intmotencARM,   sensorQuadEncoderOnI2CPort,    , AutoAssign)
//#pragma config(Sensor, I2C_5,  intmotencW,     sensorQuadEncoderOnI2CPort,    , AutoAssign)
//#pragma config(Motor,  port4,           topRight,      tmotorVex393_MC29, openLoop, driveRight, encoderPort, I2C_4)
//#pragma config(Motor,  port5,           bottomRight,   tmotorVex393_MC29, openLoop, driveRight)
//#pragma config(Motor,  port6,           topLeft,       tmotorVex393_MC29, openLoop, driveLeft)
//#pragma config(Motor,  port7,           bottomLeft,    tmotorVex393_MC29, openLoop, reversed, driveLeft)
//#pragma config(Motor,  port10,          RightWrist,    tmotorVex393_HBridge, openLoop, encoderPort, I2C_5)
////*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//add to main

//88888888888888888888888888888  arm  8888888888888888888888888888888888
///////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////
//88888888888888888888888888888    ARM MOVEMENT  8888888888888888888888888888888888

//drive the motors as commanded
void stoparm()
{
	motor[topRight]     = 0;
	motor[bottomRight]  = 0;
	motor[topLeft]      = 0;
	motor[bottomLeft]   = 0;
}

void movearm(int arm, int duration, int holdarm, int holdarmpos)
{
	if (holdarm==0)
	{
		motor[topRight]     = arm;
		motor[bottomRight]  = arm;
		motor[topLeft]      = arm;
		motor[bottomLeft]   = arm;
		//writeDebugStream(" %d",SensorValue[Wrist], " %d");
		//writeDebugStreamLine("holdarm is: %d",holdarm );  // writes the current value of int 'x' to the debug stream
		wait1Msec(duration);
	}

	//the section below commands arm to selected positions.  There is no position hold feature
	//there is no requirement for use of "abs" because count will always be positive if arm
	//is set during initialization of robot (pre auton)
	if (holdarm==1)
	{
		while ((nMotorEncoder[topRight] > (holdarmpos+40)) || (nMotorEncoder[topRight] < (holdarmpos-40)))
		{
			if (nMotorEncoder[topRight]<holdarmpos) //if below selected point, move up toward it at "arm" speed
			{
				motor[topRight]     = arm;
				motor[bottomRight]  = arm;
				motor[topLeft]      = arm;
				motor[bottomLeft]   = arm;
				wait1Msec(80); //select for arm motion smoothness - too big a number will cause arm
				//to move too fast and shoot past mid point
			}
			else if (nMotorEncoder[topRight]>holdarmpos) //if above selected point, move down toward it at "arm" speed
			{
				motor[topRight]     = -arm*2/3; //motion slowed when moving down to prevent overshoot
				motor[bottomRight]  = -arm*2/3;
				motor[topLeft]      = -arm*2/3;
				motor[bottomLeft]   = -arm*2/3;
				wait1Msec(10);
			}
			else // otherwise stop all arm motors
			{
				stoparm();
			}
		}
		stoparm();
		wait1Msec(5);
	}
}

//88888888888888888888888888888    LCD READOUT  8888888888888888888888888888888888
task lcd()
{
	int xbat;
	string num;
	string number;
	//bat num
	bLCDBacklight = true;                                    // Turn on LCD Backlight
	string mainBattery;
	string armbattery;
	string armpos;
	int mode = 1;
	int time = 500;

	while(1==1)
	{
		//888888888888888888888888888 START OF LCD CODE 888888888888888888888888888
		if(nLCDButtons != 0)
		{
			mode = nLCDButtons;
			clearLCDLine(0);// Clear line 1 (0) of the LCD
			clearLCDLine(1);// Clear line 2 (1) of the LCD
		}

		if(mode == 1)
		{
			//Display the Primary Robot battery voltage
			displayLCDString(0,0, "bat:");
			displayLCDString(1,0, "armbat:");
			sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
			sprintf(armbattery, "%1.2f%c", SensorValue[bat]/297.0,'V');
			displayLCDString(0,4, mainBattery);
			displayLCDString(1,7, armbattery);
		}
		else if(mode == 2)
		{
			displayLCDString(0,0, "arm:");
			sprintf(armpos, "%4.0f%c", nMotorEncoder[topRight]); //Build the value to be displayed
			displayLCDString(0,4, armpos);
		}
		else if(mode == 4)
		{
		}
		wait1Msec(time);
	}
}
