#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(Sensor, in1,    bat,            sensorAnalog)
#pragma config(Sensor, dgtl11, Pen1,           sensorDigitalOut)
#pragma config(Sensor, dgtl12, Pen2,           sensorDigitalOut)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Pneumatics state
int stateI = 0;

//88888888888888888888888888888    Pneumatics  8888888888888888888888888888888888
void pneumatucs(int stateI)
{
	SensorValue[Pen1] = stateI;
	SensorValue[Pen2] = stateI;
}


//88888888888888888888888888888    LCD READOUT  8888888888888888888888888888888888
task lcd()
{
	int xbat;
	string num;
	string number;
	//bat num
	bLCDBacklight = true;                                    // Turn on LCD Backlight
	string mainBattery;
	string armbattery;
	string pen1L;
	string pen2L;
	int mode = 1;
	int time = 500;

	while(1==1)
	{
		//888888888888888888888888888 START OF LCD CODE 888888888888888888888888888
		if(nLCDButtons != 0)
		{
			mode = nLCDButtons;
			clearLCDLine(0);// Clear line 1 (0) of the LCD
			clearLCDLine(1);// Clear line 2 (1) of the LCD
		}

		if(mode == 1)
		{
			//Display the Primary Robot battery voltage
			displayLCDString(0,0, "bat:");
			displayLCDString(1,0, "armbat:");
			sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
			sprintf(armbattery, "%1.2f%c", SensorValue[bat]/297.0,'V');
			displayLCDString(0,4, mainBattery);
			displayLCDString(1,7, armbattery);
		}
		else if(mode == 2)
		{
			displayLCDString(0,0, "Pen1:");
			displayLCDString(1,0, "Pen2:");
			sprintf(pen1L, "%1.2f%c", stateI); //Build the value to be displayed
			sprintf(pen2L, "%1.2f%c", stateI);
			displayLCDString(0,6, pen1L);
			displayLCDString(1,6, pen2L);
		}
		else if(mode == 4)
		{
		}
		wait1Msec(time);
	}
}
