//add to main
//#pragma config(Motor,  port1,           LeftWrist,     tmotorVex393_HBridge, openLoop, reversed)
//#pragma config(Motor,  port10,          RightWrist,    tmotorVex393_HBridge, openLoop, encoderPort, I2C_5)
////*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//add to main

///////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////
//88888888888888888888888888888    WRIST MOVEMENT  8888888888888888888888888888888888


void  movewrist (int wristspd, int duration, int aton, int wristposit)
{
	//int checking=0;//variable to allow checking of delta count check
	int wristspot = 450;
	if (aton==0)
	{
		if (SensorValue[intmotencW] <= wristspot){
			motor[RightWrist] = wristspd*0.6;
			motor[LeftWrist] = wristspd*0.6;
		}
		else if (SensorValue[intmotencW] > wristspot){
			motor[RightWrist] = wristspd;
			motor[LeftWrist] = wristspd;
		}
		//writeDebugStreamLine("wristangle is: %d",SensorValue[wrist] );
		wait1Msec(duration);
	}
	if (aton==1)
	{
		while ((abs(nMotorEncoder[RightWrist]) > (abs(wristposit)+200))||(abs(nMotorEncoder[RightWrist]) < (abs(wristposit)-200)))
		{
			if (nMotorEncoder[RightWrist] > wristposit)
			{
				motor[RightWrist] = wristspd;
				motor[LeftWrist] = wristspd;
				wait1Msec(10);
			}
			if (nMotorEncoder[RightWrist] < wristposit)
			{
				motor[RightWrist] = -wristspd;
				motor[LeftWrist] = -wristspd;
				wait1Msec(10);
			}
			else
			{
				motor[RightWrist] = 0;
				motor[LeftWrist] = 0;
			}
		}
		motor[RightWrist] = 0;
		motor[LeftWrist] = 0;
	}
}
